### PR TITLE
Version 3.x support

### PR DESCRIPTION
**Pull request by renatoalmeidaoliveira**
Add support for version 3.x fixing #70;
change behavior of the Layers checkbox (default off) fixing #67

### CODE REVIEW

**Comment by iDebugAll** [comment]
@renatoalmeidaoliveira Great job!

I have tested this in my local NetBox 3.x environment. The plugin embeds into the new NetBox Web-UI fine.

One thing before we can proceed with merge.
Please move the suggested changes regarding #67 into a separate PR as this issue is not directly related to NetBox 3.x compatibility. It requires a separate discussion and solution.

**Comment by renatoalmeidaoliveira** [comment]
@iDebugAll sure, have you tested on the older versions too? I did my best to mantain backward compatibility.

**Comment by iDebugAll** [comment]
@renatoalmeidaoliveira I have tested on NetBox 2.11 as well – it works as expected. All the changes for NB 3.x in your PR are conditional so the backward compatibility should be preserved.

**Comment by renatoalmeidaoliveira** [comment]
@iDebugAll, reverted the changes relative to #67

**Pull request merged**
